# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main


stages:
  - stage: Build
    jobs: 
        - job: BuildWebApp

          variables:
            buildConfiguration: 'Release'

          pool:
            vmImage: 'ubuntu-latest'
          steps:
            
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: true
              
          - task: SonarQubeAnalyze@5
          
          
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'

       - task: DownloadBuildArtifacts@1
         inputs:
           buildType: 'current'
           downloadType: 'single'
           artifactName: 'drop'
           itemPattern: '''**/*.zip'''
           downloadPath: '$(System.ArtifactsDirectory)'

  - stage: Deploy
    displayName: 'Deploy To Dev'
    jobs:
      - job: Deploy
      - deployment: 
        pool:
            vmImage: 'ubuntu-latest'
        environment: 'Dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Deploy Code